<footer id="footer" class="footer" role="footer">
  <div class="container">
    <div class="text-center">
      Powered by CiviHR <?php print get_civihr_version(); ?>.
      CiviHR is openly available under Version 3 of the <a target="_blank" href="http://www.gnu.org/licenses/agpl-3.0.html">GNU AGPL License</a> and can be downloaded from <a target="_blank" href="https://civihr.org">www.civihr.org</a>&nbsp;.
      <div class="footer-logo">
        <span class="chr_logo chr_logo--full chr_logo--default-size"><i></i></span>
      </div>
      <?php if ($copyright): ?>
        <div class="copyright"><?php print $copyright; ?></div>
      <?php endif; ?>
    </div>
  </div>
</footer>
